### ISSUE TITLE
Starcraft 1 Beta - different WAV compression

### ISSUE THREAD

**Issue by KaitouHAX** [ladislav-zezula/StormLib#253] opened 2022-05-08 21:36 UTC
Attempting to extract a wav file from a beta version of StarDat.mpq displays a "Failed to extract the file ... the file is corrupted and unreadable. " error message.
After doing an amateurish investigation it looks like the compression method used after the first block is 0x11 instead of an expected 0x41 or 0x81.

While it does make me wonder if it could be huffman + bzip2, the comment in the source code that bzip2 was added in warcraft 3 makes me think this is something else.

I have found a couple of beta wav files out there that were successfully extracted but not the tool that was used to extract them.
If need be, I can provide the beta.iso.

EDIT:
I have tried MPQ Editors 4.0.0.872 and 3.5.1.816.

**Comment by ladislav-zezula** [comment] 2022-05-09 06:50
Hi,
 
interesting. Could you somehow share me the MPQ? I'll look at it.
 
L.  
 
> Attempting to extract a wav file from a beta version of StarDat.mpq displays a "Failed to extract the file ... the file is corrupted and unreadable. " error message.
> After doing an amateurish investigation it looks like the compression method used after the first block is 0x11 instead of an expected 0x41 or 0x81.
> While it does make me wonder if it could be huffman + bzip2, the comment in the source code that bzip2 was added in warcraft 3 makes me think this is something else.
> I have found a couple of wav files out there that were successfully extracted but not the tool that was used to extract them.
> If need be, I can provide the beta.iso.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

-- 
S pozdravem,
 Ladislav Zezula
***@***.***

**Comment by KaitouHAX** [comment] 2022-05-09 07:47
Sure thing.

Here's the link with the beta StarDat.mpq and storm.dll and a wav file that i found already extracted.
[Starcraft Beta Drive](https://drive.google.com/drive/folders/17F6kjT0_ibS3i91HUSWw3eVscnVXktIT?usp=sharing)

**Comment by ladislav-zezula** [comment] 2022-05-10 13:32
Looks like this particular release of `storm.dll` has different bit values for the decompression routines.
```
0x10 = Decompress_ADPCM_mono
0x20 = Decompress_ADPCM_stereo
```
whilst in other releases of `storm.dll` (and in StormLib) is it:
```
0x80 = Decompress_ADPCM_mono
0x40 = Decompress_ADPCM_stereo
```
I'll see what can I do.

**Comment by ladislav-zezula** [comment] 2022-05-11 03:53
Could you please also check the ISO? There should be music files, I want to know if they can't be extracted either.

**Comment by KaitouHAX** [comment] 2022-05-11 06:52
> Could you please also check the ISO? There should be music files, I want to know if they can't be extracted either.

Same extraction issue, but this time it wants 0x21.
I've added INSTALL.EXE mpq file to the drive link.

**Comment by ladislav-zezula** [comment] 2022-05-11 06:58
Ooookey. So hard-coded check for just StarDat.mpq is not enough. I'll download it and refine the code.
BTW, could you add the entire ISO? I'll add it to my collection of the Blizzard games :-)

**Comment by KaitouHAX** [comment] 2022-05-11 09:33
I've added the iso to the drive.
So after all, was switching those byte values enough to uncompress it?

**Comment by ladislav-zezula** [comment] 2022-05-11 19:02
> So after all, was switching those byte values enough to uncompress it?

No. Decompression succeeded, but the data is corrupt - different than the WAVE you sent and also different from what `storm.dll` extracts. I'll have to dig deeper into that BETA ADPCM decompression to see where's the difference.

**Comment by ladislav-zezula** [comment] 2022-05-12 13:48
I implemented the decompression. Note that an attempt to compress the files back will lead to them being unreadable by the game. It's not merged yet, but you can already try the new build of MPQ Editor.

* StormLib: https://github.com/ladislav-zezula/StormLib/tree/LZ_SupportStarcraftBeta
* MPQEditor: http://www.zezula.net/download/mpqeditor_en_sc1b.zip

**Comment by KaitouHAX** [comment] 2022-05-13 17:24
Ah, thank you.
And no worries i have no plan to compress files back.
I suppose this issue is closed now?

**Comment by ladislav-zezula** [comment] 2022-05-14 05:27
It's not closed yet. I want a bit better integration, plus I still have to run regression tests against the new code.

**Comment by ladislav-zezula** [comment] 2022-05-15 18:58
[Merged](https://github.com/ladislav-zezula/StormLib/pull/255). Thanks for the bug report.

**Closed by ladislav-zezula** 2022-05-15 18:58 UTC
