### ISSUE TITLE
Can't edit war3map.j in mpq editor

### ISSUE THREAD

**Issue by juvian** [ladislav-zezula/StormLib#257] opened 2022-06-08 20:45 UTC
Using latest mpq editor (4.0.0.872) with this map https://mega.nz/file/NqRFEKzZ#8MUHL_lYaaOTGONjMNRm5SeFwDhxM7bt67EGQ3clEC4 when drag and dropping a new war3map.j file it asks to replace it, I accept but it does not get replaced and remains the same. 
Using older v3.5.1.814 version it does work
Using older v3.6.0.858 it does not work
Using older v3.6.0.844 it does not work

**Comment by juvian** [comment] 2022-06-08 22:29
Tested more, actually its same bug in all mpq versions, its just that v3.5.1.814 shows the new one added but when you close and open mpq again it shows older one again. In order to replace the file with latest mpq I managed to get it working by:
1. add new war3map.j, will still show old
2. delete war3map.j, will show none
3. close mpq
4. reopen mpq
5. it will show the new war3map.j

Checking the file properties, I see that before replacing, it looks like
![image](https://user-images.githubusercontent.com/5660396/172728064-112c19bd-43bf-4f63-b89f-0dce546477f2.png)
After replacing, hash # changes to 0
After delete + reopen, it shows
![image](https://user-images.githubusercontent.com/5660396/172728175-8779ecca-d13d-4336-9966-5c9f6a917313.png)

I think new file gets a lower hash number so mpq considers it not the latest version of the file?

**Comment by ladislav-zezula** [comment] 2022-06-09 06:14
Thanks for the bug report. I'll check as soon as I have time.

**Comment by ladislav-zezula** [comment] 2022-06-11 06:05
The bug is caused by slightly different searching algorithm in `SFileOpenFileEx` vs `SFileAddFileEx`. Whilst the first one uses `GetFileEntryLocale`, which has been very carefully adapted to work the same like the one in Warcraft III, functions `SFileAddFileEx` and `SFileSetFileLocale` use `GetFileEntryExact`. Normally, it's not a problem but look at the hash table in this map:
```
00000BE0	FFFFFFFF	FFFFFFFF	FFFF	00FF	FFFFFFFF	
00000BE1	FFFFFFFF	FFFFFFFF	FFFF	00FF	FFFFFFFF	
00000BE2	FFFFFFFF	FFFFFFFF	FFFF	00FF	FFFFFFFF	
00000BE3	ED373F68	80C59765	0000	0000	0000009F	File00000159.blp
00000BE4	FFFFFFFF	FFFFFFFF	FFFF	00FF	FFFFFFFF	
00000BE5	42BAD41A	D4C71D2D	0000	0000	00000194	File00000404.blp
00000BE6	C99707E7	95B8144E	0000	0000	00000351	war3map.j                   <======= Found when replacing
00000BE7	39E4F8C8	B8F9C391	0000	0000	0000011D	File00000285.blp
00000BE8	D128A402	CE172410	0000	0000	0000006C	File00000108.blp
00000BE9	52B3367F	7B29E116	0000	0000	000002FF	File00000767.blp
00000BEA	1544E214	2577CF6A	0000	0000	000004ED	File00001261.mp3
00000BEB	F43B866B	A62CFC10	0000	0000	000001B7	File00000439.blp
00000BEC	C99707E7	95B8144E	0000	0000	00000A72	war3map.j                   <======= Found when opening
00000BED	430D7FA0	81D6C222	0000	0000	00000400	File00001024.mp3
00000BEE	0D677E63	0AD89F3C	0000	0000	0000046C	File00001132.blp
00000BEF	F54E6B5F	166945BF	0000	0000	00000092	War3map.w3u
00000BF0	491BA688	1EC83D7F	0000	0000	00000129	File00000297.mp3
```
I'll make a fix and also add the map you sent into regression tests, so this won't happen again.

**Comment by ladislav-zezula** [comment] 2022-06-11 06:17
This is the build that has the bug fixed. Please, consider it a preview version, there may be other problems with this MPQ.
http://zezula.net/download/mpqeditor_en_juvian.zip
The change is not even in StormLib's repository until I finish regression tests, which will again take some time.

**Comment by juvian** [comment] 2022-06-11 17:52
Really appreciate you still fixing things along the years. Can close issue if it passes regression tests. Thanks!

**Comment by ladislav-zezula** [comment] 2022-06-12 18:49
Fixed in https://github.com/ladislav-zezula/StormLib/pull/258

**Closed by ladislav-zezula** 2022-06-12 18:49 UTC

**Comment by ladislav-zezula** [comment] 2022-06-12 19:23
MPQ Editor recompiled and uploaded. However, with such screwed MPQs like the one you sent, there may be other issues.
