### ISSUE TITLE
w3n file permanently read only after crossing 2GB threshold

### ISSUE THREAD

**Issue by Wiimeiser** [ladislav-zezula/StormLib#306] opened 2023-09-20 11:26 UTC
After manually inserting multiple files into a w3n archive and increasing its size to over 2GB, the file, in addition to being unable to be loaded in the World Editor, is automatically marked as Read Only on being opened in the MPQ Editor, and there seems to be no way to disable this so that the issue can actually be corrected.

**Comment by ladislav-zezula** [comment] 2023-09-20 12:17
Well, just don't do that. I don't think that Warcraft III is able to handle that large maps, because MPQ version 1, which is uses, can't go over 2 GB.

**Comment by Wiimeiser** [comment] 2023-09-20 12:23
Okay, that's fair. Though then the issue becomes why the MPQ Editor allows making the file bigger, then goes into permanent read-only mode on reopening the file.

**Comment by ladislav-zezula** [comment] 2023-09-20 13:07
I'll try to reproduce. Maybe there is a gap in the size check for MPQs version 1.

**Comment by ladislav-zezula** [comment] 2023-09-22 23:49
Fixed in commit https://github.com/ladislav-zezula/StormLib/commit/cb56fff1a5aa1fd3b69c92c38dd07aec4ae28dec

**Closed by ladislav-zezula** 2023-09-22 23:49 UTC
