### ISSUE TITLE
.mix file opens partially then stops

### ISSUE THREAD

**Issue by Killerwatts** [ladislav-zezula/StormLib#152] opened 2019-03-17 02:52 UTC
Hi, I was able to open this .mix file http://www.mediafire.com/file/abwt7k62t2ru7uo/acgpatch.mix/file. However, despite the size, it only contained one file; a loadingscreen.mdx. The MPQ editor appears to open the file partially before stopping. Are the files somehow hidden?

**Comment by Unryze** [comment] 2019-03-17 09:28
It has Themida applied on it, you will need either to unpack Themida or well, hope that Ladik will add support to reading of files from Themida.

In that file it is a "true" file being masked and the other part is simply an additional MPQ that serves as the primary loaded data, etc.

In short, right now there is no way to open it correctly.

**Comment by ladislav-zezula** [comment] 2019-03-17 09:41
If a mix file (a DLL file, in fact) unpacks itself and then feeds Warcraft III with an inside MPQ, then there's not much I can do. The problem is that I don't understand the mechanism of how the MIX files give data to the game.

**Comment by Unryze** [comment] 2019-09-10 09:17
BOOL APIENTRY DllMain( HINSTANCE hinstDLL, DWORD DwReason, LPVOID lpReserved ) {
	Storm::Init();

	if ( DwReason == DLL_THREAD_ATTACH ) {
		DisableThreadLibraryCalls(hinstDLL);
		GetModuleFileName( hinstDLL, DllPath, 2048 );
		Storm::OpenArchive( DllPath, 0, 0, &Handle );
	}
	else if ( DwReason == DLL_THREAD_DETACH ) { Storm::CloseArchive( Handle ); }
	return TRUE;
}

Forgot to add the code, this is how .mix is loaded into the game, the dll's code is above, the MPQ data is added at the bottom via hex.

**Comment by Unryzesinshluhi** [comment] 2019-09-16 22:56
<a href="https://imgbb.com/"><img src="https://i.ibb.co/6Ykxhzm/fc096595b2f3fe37eb19b9261fac5d11.jpg" alt="fc096595b2f3fe37eb19b9261fac5d11" border="0"></a>

**Comment by 2020karaulov2020** [comment] 2020-03-25 13:50
> If a mix file (a DLL file, in fact) unpacks itself and then feeds Warcraft III with an inside MPQ, then there's not much I can do. The problem is that I don't understand the mechanism of how the MIX files give data to the game.

@ladislav-zezula 

1. Non protected mix archives just used SFile::OpenArchive from Storm.dll ( fixed in https://github.com/ladislav-zezula/StormLib/issues/169 )
2. Protected (with themida) used hook some functions from Storm.dll (IAT) for open file from memory (file memory mapping, etc)

1. Just opened as MPQ archive 
2. Manually dump whole process and find MPQ header using HEX EDITOR ))))

This is option number 2. For unpacking need execute this file as .dll, and possible get viruses while unpacking.
@Killerwatts 
I got unpacked archive http://www.mediafire.com/file/vuni14j45e9o3lw/acgpatch.mix/file

**Comment by ladislav-zezula** [comment] 2020-03-25 15:43
I am not going to load 3dparty MIX files. Besides danger of running untrusted code, it won't work in 64-bit builds of Warcraft III.

**Closed by ladislav-zezula** 2020-03-25 15:43 UTC
